apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1 #Replicas is a number of pods we want to create running a particular pods
  selector: #Selectors basically looks all the selected pods thats are created. Find all the pods that match labels app: posts
    matchLabels:
      app: event-bus
  template: # Everything inside Template basically a pod speciication or information or pod config file
    metadata:
      labels:
        app: event-bus 
    spec:
      containers:
        - name: event-bus
          image: subhajit601/event-bus
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005 #Actual port which my code is listening

